### ISSUE TITLE
Override TextEncoder()

### ISSUE THREAD

**Issue by eclipse1985** [inexorabletash/text-encoding#30] opened 2015-04-12 23:57 UTC
Hi all,

chrome has its own implementation of TextEncoder(), but it doesn't support the legacy encoding.

I use your implementation simply replacing "TextEncoder" with "NewTextEncoder" directly editing your source code.

There is a better way?

Thanks

**Comment by inexorabletash** [comment] 2015-06-14 04:00
Duplicate of #25 

(But the answer is: no, there's not a better way yet)

**Closed by inexorabletash** 2015-06-14 04:00 UTC
